name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test || echo "No tests defined"
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      
    - name: Configure Docker to use Google Cloud
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
    - name: Build and Push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-catalog-repo/product-catalog-service:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-catalog-repo/product-catalog-service:${{ github.sha }}
        
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0.6.0
      with:
        service: product-catalog-service
        image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/product-catalog-repo/product-catalog-service:${{ github.sha }}
        region: us-central1
        env_vars: |
          NODE_ENV=production
          PORT=8080
        secrets: |
          MONGODB_URI=mongodb-uri:latest
          JWT_SECRET=jwt-secret:latest